name: flutter_basic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cloud_firestore: ^5.6.3
  flutter:
    sdk: flutter
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1

flutter:
  uses-material-design: true
